### PR TITLE
feat: Resolved float and double union marshalling issue

### PR DESCRIPTION
**Pull request by mescanne**
Float and double values were not decoding as unions -- but are encoded as unions -- and thus broke the marshal/unmarshal roundtrip.

A test was created (including for int and sint) which failed appropriately, and then the fix was applied. Some code was refactored in a minor way to align with the rest of the types.

### CODE REVIEW

**Comment by mescanne** [comment]
Please let me know if this fix can be merged -- if not, I will need to use a different library or approach. This library is, otherwise, solid and well put together!

Thank you.

Mark

**Review by m4mm4r — COMMENTED** [review]
Thanks for this enhancement. 

Realize that there are no contribution guidelines here. But we're using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), which is why the review pipeline is failing. Do you mind updating the commit message to follow the pattern. Here it would be that you just prefix your message with `feat: `. 

Just ask me for a re-review after and I'll approve. Looks good.

Thanks!

**Comment by mescanne** [comment]
I've made the change in both the git commit and the PR description.

**Review by m4mm4r — APPROVED** [review]
Thanks for contributing

**Pull request merged**
